apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-cloudinit-{{ .counter }}
type: Opaque
stringData:
  userdata: |
    #cloud-config
    user: {{ .vmUser | default "cloud-user" }}
    password: redhat
    chpasswd: { expire: False }
    {{- if .enablePerfTest }}
    runcmd:
      # Install memory testing tools
      - yum install -y stress-ng htop numactl || dnf install -y stress-ng htop numactl || true
      # Create memory performance test script
      - |
        cat > /usr/local/bin/memory-performance-test.sh << 'EOFSCRIPT'
        #!/bin/bash
        LOG_FILE="/var/log/memory-performance.log"
        
        echo "Starting high memory performance test" | tee -a $LOG_FILE
        echo "Total memory: $(free -h | grep '^Mem:' | awk '{print $2}')" | tee -a $LOG_FILE
        echo "Available memory: $(free -h | grep '^Mem:' | awk '{print $7}')" | tee -a $LOG_FILE
        
        # Test memory with stress-ng
        echo "Running stress-ng memory test (4 workers, 10GB each)..." | tee -a $LOG_FILE
        stress-ng --vm 4 --vm-bytes 10G --vm-method all --verify -t 60s 2>&1 | tee -a $LOG_FILE
        
        # Extended memory stress test with larger allocation
        TOTAL_MEM_GB=$(free -g | grep '^Mem:' | awk '{print $2}')
        TEST_MEM_GB=$((TOTAL_MEM_GB * 80 / 100))  # Use 80% of total memory
        
        echo "Running extended memory test with ${TEST_MEM_GB}GB allocation..." | tee -a $LOG_FILE
        stress-ng --vm 8 --vm-bytes ${TEST_MEM_GB}G --vm-method all --verify -t 300s 2>&1 | tee -a $LOG_FILE
        
        # Memory bandwidth test
        echo "Testing memory bandwidth..." | tee -a $LOG_FILE
        stress-ng --stream 4 --stream-L3-size 32M -t 60s 2>&1 | tee -a $LOG_FILE
        
        # NUMA memory test if available
        if command -v numactl &> /dev/null; then
            echo "Testing NUMA memory performance..." | tee -a $LOG_FILE
            numactl --hardware 2>&1 | tee -a $LOG_FILE
            stress-ng --vm 2 --vm-bytes 5G --vm-method numa -t 60s 2>&1 | tee -a $LOG_FILE
        fi
        
        echo "Memory performance test completed. Results in $LOG_FILE" | tee -a $LOG_FILE
        
        # Continuous memory monitoring
        echo "Starting continuous memory monitoring..." | tee -a $LOG_FILE
        while true; do
            echo "$(date): Memory usage: $(free -h | grep '^Mem:')" >> /var/log/memory-monitor.log
            sleep 60
        done &
        EOFSCRIPT
      - chmod +x /usr/local/bin/memory-performance-test.sh
      # Start memory test in background
      - nohup /usr/local/bin/memory-performance-test.sh > /var/log/memory-test-output.log 2>&1 &
    {{- end }}

