apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-cloudinit-{{ .counter }}
type: Opaque
stringData:
  userdata: |
    #cloud-config
    user: {{ .vmUser | default "cloud-user" }}
    password: redhat
    chpasswd: { expire: False }
    {{- if .enablePerfTest }}
    runcmd:
      # Install performance testing tools
      - yum install -y fio hdparm smartmontools sysstat || dnf install -y fio hdparm smartmontools sysstat || true
      # Format the large disk with XFS
      - mkfs.xfs -f /dev/vdc || true
      - mkdir -p /mnt/largedisk
      - mount /dev/vdc /mnt/largedisk || true
      # Create performance test script
      - |
        cat > /usr/local/bin/disk-performance-test.sh << 'EOFSCRIPT'
        #!/bin/bash
        DEVICE="/dev/vdc"
        MOUNT_POINT="/mnt/largedisk"
        LOG_FILE="/var/log/disk-performance.log"
        
        echo "Starting large disk performance test on $DEVICE" | tee -a $LOG_FILE
        echo "Disk size: $(lsblk $DEVICE | tail -1 | awk '{print $4}')" | tee -a $LOG_FILE
        
        # Test raw read performance
        echo "Testing raw read performance..." | tee -a $LOG_FILE
        hdparm -t $DEVICE 2>&1 | tee -a $LOG_FILE
        
        # Test sequential read performance
        echo "Testing sequential read with FIO..." | tee -a $LOG_FILE
        fio --name=seq_read --filename=$MOUNT_POINT/testfile --size=10G --rw=read --bs=1M --direct=1 --numjobs=1 --runtime=60 --time_based=1 2>&1 | tee -a $LOG_FILE
        
        # Test sequential write performance
        echo "Testing sequential write with FIO..." | tee -a $LOG_FILE
        fio --name=seq_write --filename=$MOUNT_POINT/testfile --size=10G --rw=write --bs=1M --direct=1 --numjobs=1 --runtime=60 --time_based=1 2>&1 | tee -a $LOG_FILE
        
        # Test random I/O performance
        echo "Testing random I/O performance..." | tee -a $LOG_FILE
        fio --name=rand_rw --filename=$MOUNT_POINT/testfile --size=10G --rw=randrw --bs=4k --direct=1 --numjobs=4 --runtime=60 --time_based=1 --iodepth=16 2>&1 | tee -a $LOG_FILE
        
        echo "Disk performance test completed. Results in $LOG_FILE" | tee -a $LOG_FILE
        EOFSCRIPT
      - chmod +x /usr/local/bin/disk-performance-test.sh
      # Start performance test in background
      - nohup /usr/local/bin/disk-performance-test.sh > /var/log/perf-test-output.log 2>&1 &
    {{- end }}

